# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: kramdown 
include: ['_pages/', 'images', 'files']

# configuration required for some pages

title: c0g
author: Tom Nickson

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid


github:
  username: c0g


# disqus:
#   id: disqusid
