# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
include: ['_phd/', '_pages/', 'images']

# configuration required for some pages

title: c0g
author: Tom Nickson
email: tron@robots.ox.ac.uk

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid


github:
  username: c0g

# disqus:
#   id: disqusid
